### ISSUE TITLE
GoldSrc support

### ISSUE THREAD

**Issue by ViBE-HU** [obozrenie/obozrenie#6]
Please add support for GoldSrc games like Counter-Strike Half-Life, etc. if possible. It would be still useful.

**Comment by fred0r** [comment]
Thats really a Issue :/
Slightly offtopic: There's really no real HLSW replacement on Linux ?

**Comment by vorot93** [comment]
I have not found a reliable way to differentiate between Counter-Strike 1.6 and Counter-Strike Source servers by just altering QStat flags. Both games use `cstrike` identifier and there is no standard rule set for either. More than that, I have to remove CS:S because of this mess.

Half-Life Deathmatch: Source has been in for very long time. There are no other Linux GoldSrc-based multiplayer games, hence this request is moot.
